version: "3.1"

services:
  pgsql-db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "ffxivtools"
      POSTGRES_USER: "ffxiv"
      POSTGRES_PASSWORD: "supersecret"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mysql-db:
      image: mysql:8.3
      container_name: db
      restart: always
      environment:
          MYSQL_DATABASE: "ffxivtools"
          MYSQL_USER: "ffxiv"
          MYSQL_PASSWORD: "supersecret"
          MYSQL_ROOT_PASSWORD: "supersecret"
      ports:
          - "3306:3306"
      volumes:
          - ./mysql:/var/lib/mysql
