version: "3.1"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "ffxivtools"
      POSTGRES_USER: "ffxiv"
      POSTGRES_PASSWORD: "supersecret"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
